language: java
jdk:
- oraclejdk8
- oraclejdk7
install: mvn install -DfinalName=IsMyWebsiteDown -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: releases
  api_key:
    secure: Qzotp3hMt4fwJz0x7tCYnpajhVZhdLUeoUKbSWkPOxG/Jp5NqqwTiCtIv88EOXUwpeE13vC4ULh4Z8SqzhJsUCuTvMW28YK2IjWbQcjHvnzLk86l9pY4v6zPoGIp1Qt1bsZBAbh6wmim6bIF6/13VC85oVry1cu4m87SHJ2LyBE=
  file: /home/travis/build/MarvinMenzerath/IsMyWebsiteDown/target/IsMyWebsiteDown.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    jdk: oraclejdk8